project:
  type: website

execute:
  freeze: auto

website:
  title: "MicroGen 2026"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    logo: "website-assets/images/KLEB-CASAVA.png"
    right:
      - text: "Practical Guides"
        menu:
          - text: 'Day 0 - Pre-Workshop'
            # href: day-0/instructions/index.qmd
            href: guides.qmd
          - text: 'Day 1'
            href: day-1/instructions/index.qmd
          - text: 'Day 2'
            href: day-2/instructions/index.qmd
          - text: 'Day 3'
            href: day-3/instructions/index.qmd
          - text: 'Day 4'
            href: day-4/instructions/index.qmd  
      - text: "Lecture Slides"
        menu:
          - text: 'Day 0'
            href: day-0/slides/MicroGen2026_Day0.pdf
            target: '_blank'
          - text: 'Day 1'
            href: day-1/slides/MicroGen2026_Day1.pdf
            target: '_blank'
          - text: 'Day 2'
            href: day-2/slides/MicroGen2026_Day2.pdf
            target: '_blank'
          - text: 'Day 3'
            href: day-3/slides/MicroGen2026_Day3.pdf
            target: '_blank'
          - text: 'Day 4'
            href: day-4/slides/MicroGen2026_Day4.pdf
            target: '_blank'
    tools:
        - icon: github
          href: https://github.com/molepi-oucru/MicroGen-2026
  sidebar:
    - id: practical-guides
      title: "Practical Guides"
      contents:
        - section: "Practical Guides"
          href: guides.qmd
          contents:
            - section: "Day 0 - Pre-Workshop"
              href: day-0/instructions/index.qmd
              contents:
                - section: "0.1 Setup your workspace"
                  href: day-0/instructions/setup-environment.qmd
                  contents:
                    - text: "Overview"
                      href: day-0/instructions/setup-environment.qmd
                    - text: "Windows 10/11 setup"
                      href: day-0/instructions/setup-windows.qmd
                    - text: "macOS setup"
                      href: day-0/instructions/setup-macos.qmd
                    - text: "Ubuntu setup"
                      href: day-0/instructions/setup-ubuntu.qmd
                    - text: "Bioinformatics apps"
                      href: day-0/instructions/setup-bioinformatics-apps.qmd
                    - text: "Server access"
                      href: day-0/instructions/setup-server-access.qmd
                    - text: "Verification checklist"
                      href: day-0/instructions/setup-verification.qmd
                    - text: "Troubleshooting and FAQs"
                      href: day-0/instructions/setup-troubleshooting-faq.qmd
                    - text: "Advanced R in VS Code"
                      href: day-0/instructions/setup-r-vscode.qmd
                - day-0/instructions/linux-basics.qmd
                - day-0/instructions/final-quiz.qmd
            - section: "Day 1"
              href: day-1/instructions/index.qmd
              contents:
                - day-1/instructions/introduction.qmd
                - day-1/instructions/genome-view.qmd
                - day-1/instructions/raw2assembly.qmd
            - section: "Day 2"
              href: day-2/instructions/index.qmd
              contents:
                - day-2/instructions/post-assembly.qmd
                - day-2/instructions/hybrid-assembly.qmd
                - day-2/instructions/gene-alignment.qmd
            - section: "Day 3"
              href: day-3/instructions/index.qmd
              contents:
                - day-3/instructions/mapping.qmd
                - day-3/instructions/phylotree.qmd
            - section: "Day 4"
              href: day-4/instructions/index.qmd
              contents:
                - section: "mNGS in clinical microbiology"
                  contents:
                    - text: "4.1 Workflow Setup" 
                      href: day-4/instructions/vietnamese-healthy-gut-microbiome.qmd
                    - text: "4.2 Taxonomy Analysis" 
                      href: day-4/instructions/vietnamese-healthy-gut-taxonomy.qmd
                    - text: "4.3 AMR Analysis & Summary" 
                      href: day-4/instructions/vietnamese-healthy-gut-amr.qmd
                - section: "mNGS in pathogen detection"
                  contents:
                    - text: "4.4 Clinical Case" 
                      href: day-4/instructions/clinical-reasoning.qmd
                    - text: "4.5 Signal Analysis" 
                      href: day-4/instructions/clinical-reasoning-analysis.qmd

format:
  html:
    theme: cosmo
    css: website-assets/styles.css
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
    link-external-newwindow: true
    toc: true
    code-copy: true
    code-block-bg: true
    # code-overflow: wrap
    code-line-numbers: true
    smooth-scroll: true
    anchor-sections: true
  # pdf: 
  #   documentclass: report
  #   geometry:
  #     - top=20mm
  #     - left=20mm
  #     - heightrounded
  #   # mainfont: "TeX Gyre Heros"
  #   # sansfont: "TeX Gyre Heros"
  #   code-overflow: wrap
  #   colorlinks: true
  #   code-line-numbers: true
  #   include-in-header:
  #     - text: |
  #         \usepackage{fvextra}
  #         \fvset{
  #           breaklines=true,
  #           breakanywhere=true,
  #           breakbytokenanywhere=true
  #         }
  #         \AtBeginDocument{
  #           \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
  #             breaklines,
  #             breakanywhere,
  #             breakbytokenanywhere,
  #             commandchars=\\\{\}
  #           }
  #         }
          





