project:
  type: website

execute:
  freeze: auto

website:
  title: "MicroGen 2026"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    logo: "website-assets/images/KLEB-CASAVA.png"
    right:
      - text: "Practical Guides"
        menu:
          - text: 'Day 0'
            href: day-0/instructions/index.qmd
          - text: 'Day 1'
            href: day-1/instructions/index.qmd
          - text: 'Day 2'
            href: day-2/instructions/index.qmd
          - text: 'Day 3'
            href: day-3/instructions/index.qmd
          - text: 'Day 4'
            href: day-4/instructions/index.qmd  
      - text: "Lecture Slides"
        menu:
          - text: 'Day 0'
            href: day-0/slides/MicroGen2026_Day0.pdf
            target: '_blank'
          - text: 'Day 1'
            href: day-1/slides/MicroGen2026_Day1.pdf
            target: '_blank'
          - text: 'Day 2'
            href: day-2/slides/MicroGen2026_Day2.pdf
            target: '_blank'
          - text: 'Day 3'
            href: day-3/slides/MicroGen2026_Day3.pdf
            target: '_blank'
          - text: 'Day 4'
            href: day-4/slides/MicroGen2026_Day4.pdf
            target: '_blank'
    tools:
        - icon: github
          href: https://github.com/molepi-oucru/MicroGen-2026
  sidebar:
    - id: practical-guides
      title: "Practical Guides"
      contents:
        - section: "Practical Guides"
          contents:
            - text: "Day 0"
              href: day-0/instructions/index.qmd
            - section: "Day 1"
              href: day-1/instructions/index.qmd
              contents:
                - day-1/instructions/introduction.qmd
                - day-1/instructions/genome-view.qmd
                - day-1/instructions/raw2assembly.qmd
            - section: "Day 2"
              href: day-2/instructions/index.qmd
              contents:
                - day-2/instructions/post-assembly.qmd
                - day-2/instructions/hybrid-assembly.qmd
                - day-2/instructions/gene-alignment.qmd
            - section: "Day 3"
              href: day-3/instructions/index.qmd
              contents:
                - day-3/instructions/mapping.qmd
                - day-3/instructions/phylotree.qmd
            - text: "Day 4"
              href: day-4/instructions/index.qmd

format:
  html:
    theme: cosmo
    css: website-assets/styles.css
    extensions:
      - quarto-ext/fontawesome
    link-external-newwindow: true
    toc: true
    code-copy: true
    code-block-bg: true
    smooth-scroll: true
    anchor-sections: true






