---
title: "1.3 From raw sequencing data to assemblies"
author: "Nguyen MTS"
date: "2026-05-12"
---

# Introduction

From now until the end of Day-3, we will work with a real-world dataset: a nosocomial *K. pneumoniae* outbreak in Italy.

The dataset is under the BioProject ID: **_PRJNA1260529_**, acompanied by the publication of [Captani *et al*, Euro Surveill, 2026](https://doi.org/10.2807/1560-7917.ES.2026.31.10.2500457). It describes an outbreak of multidrug-resistant and carbapenemase-producing *K. pneumoniae* ST147 in the sub-intensive care unit (S-ICU) of a tertiary care hospital in Italy between mid-February and early March 2025. NDM-producing *K. pneumoniae* isolates were sequenced using both Illumina short-read and Oxford Nanopore long-read technologies. The sequencing data helped illuminating the transmission dynamics of the outbreak and the genomic features of the isolates.

Using this dataset, we will learn how to transform "raw" sequencing data into "intepretable" genomes, and get a practical experience with a typical workflow in genomic epidemiology in the context of infectious disease outbreaks.

Our work-flow will comprise the following main processes:

1.  Quality assessment (and improvement) of raw sequencing data
2.  Genome assembly
3.  Species identification and MLST typing
4.  AMR gene profiling
5.  Genome annotation
6.  Gene variation analysis
7.  Phylogenetic analysis

This module will guide you through the first 2 processes.

We hope you will enjoy the *flow*. Now, let's begin!

# Data directory

If you have completed Day-0, you probably have downloaded the dataset in the last exercise. But if you haven't, no worries, we’ve got you covered! The data is pre-loaded on your instance under the directory:

`/microgen2026/PRJNA1260529/`

This directory contains all the raw sequencing data files from the study, both from short-read sequencing (Illumina MiSeq) and long-read sequencing (Oxford Nanopore).

All metadata information of the dataset, such as sample name and sequencing technique for each data file, are stored in the tab-delimited file:

`/microgen2026/day-1/PRJNA1260529.metadata.tsv`.

We will first learn and practice on the short-read data, while long-read sequencing will be introduced later in module [2.3](../../day-2/instructions/hybrid-assembly.qmd).

We have already taken out the short-read data to a new directory for you: 

`/microgen2026/day-1/raw_shortread/`

As the `/microgen2026/` is a shared directory for the whole course, please copy it to your home directory:

``` {.bash code-line-numbers="false"}
cp -r /microgen2026/day-1/raw_shortread/ ~/
```

Now you can work on it without disrupting your classmates ✔️

Let's take a look at the files in the `raw_shortread` directory:

``` {.bash code-line-numbers="false"}
ls raw_shortread/
```

You shall see a directory structure that looks like this:

``` {.bash code-line-numbers="false"}
├── raw_shortread 
│   ├── 925Kp_1.fastq.gz 
│   ├── 925Kp_2.fastq.gz 
│   ├── 930Kp_1.fastq.gz 
│   ├── 930Kp_2.fastq.gz 
│   ├── ... 
```

Try to answer the following questions:

- How many files are there?
- What are the sizes of these files?
- What do the file names tell you?

::: {.callout-note collapse="false"}
## Challenge

Check if the files are truly corresponding to short-read sequencing data, but not the long-read, using command-lines.

*Hint: Use the metadata file. Loop (recursively run) through the forward read files to get the sample names.*

<details>

<summary>Code</summary>

``` {.bash code-line-numbers="false"}
metadata="path-to-metadata-file" 
for file in *_1.fastq.gz; do # start of the loop

    sample=${file%%_*}; # split the filename by the character "_" and get the first part - the sample name
    
    # add your code to search for the sample and get its sequencing tech in the metadata file

done # end of the loop
```

</details>
:::

# FASTQ files

Raw sequencing data is stored in FASTQ format. The filename usually ends with `.fastq` (or `.fq`), or `.fastq.gz` (or `.fq.gz`) if they are compressed.

For paired-end short-reads, each sample has two files: one for forward reads (`_1`) and one for reverse reads (`_2`).

In our dataset, the files are named as `{sample-name}_1.fastq.gz` and `{sample-name}_2.fastq.gz` for forward and reverse reads, respectively.

Each FASTQ file contains four lines for every single read:

- **Sequence ID**: The "name" of the read (starts with `@`)
- **The DNA sequence**: The actual A, T, C, and G bases.
- **Separator**: Usually just a `+` sign or `+` followed by the sequence ID.
- **Quality Scores**: Symbols representing how confident the sequencing machine is about each base (Phred scores).

Let's try printing out the first 12 lines of one of the FASTQ files:

``` {.bash code-line-numbers="false"}
zcat raw_shortread/925Kp_1.fastq.gz | head -n12; # zcat is cat for gzipped files
```

The output should look like below:

```bash
@SRR33475255.1 VH01637:40:AAGVVC2M5:1:1101:22246:1000 length=301
AAGTACCTCAACGGCCATTCCGATGTCGTCGCCGGCCTGGCGGTGGTTGGCGATAACTCCGGGCTCGCGGAAAAGCTTGGCTATCTGCAGAATGCGGTAGGCGGCGTGCTTGACCCGTTCAGCAGCTTCCTGACGCTGCGCGGCATCCGTACCCTGGCGCTGCGGATGGAGCGCCACAGCGCGAACGCGCTGCAGCTCGCCGAATGGCTGGAACAGCAGCCGGAAGTGGAGCGAGTCTGGTTTCCCTGGCTGGCCTCGCACCCGCATCATCAGCTGGCGCGCCAGCAAATGGCCCTGCCCG
+SRR33475255.1 VH01637:40:AAGVVC2M5:1:1101:22246:1000 length=301
CCCCCC*CCCCCCCCCCCCC5CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC5C5CCCCCCCCCCCCCCCCCCCCCC5CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC*CCCCCCCCCCC5CCCCCCCC5CCCCC5CCCCCCC5CCCCCCCCCCCCCCC*CCCCCCCCCCCCCC5*CCCC5CCCCCC5CCCC*CCCCCCCCCCCCCCCCCCCCCC*CCC*C5CCCCCCCCCCCC*CCCCCCCCCCCC5CCCCCCCCC*CC*CCC55*5CC55*5C*C555C5CCC5C**
@SRR33475255.2 VH01637:40:AAGVVC2M5:1:1101:28797:1000 length=199
ATGTTGACCTGTAAGAACGAAAACACTGTTCTTTCCTGTGTGTCTTCCATTTCTTAGAACAACGTGCATATCTATTCTTGCATTTAAAGTCGCTTCGTCAATCCCCTATATTTCTAGGCGGGTATCTTTTAATGCAGATGGGAATACTCATCTCATAAACAGTGAATAATTATAAAGATGAAATCACACGGTTCTATTT
+SRR33475255.2 VH01637:40:AAGVVC2M5:1:1101:28797:1000 length=199
*CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC5CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC5CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC5CCCCCCCCC*CCCCC5CCC*5CCCCCCC5CCCCCCC5CCC*C55CCCCC5
@SRR33475255.3 VH01637:40:AAGVVC2M5:1:1101:32244:1000 length=295
CGGTAACTGATGCCGTATTTGCAGTACCAGCGTACGGCCCACAGAATGATGTCACGCTGAAAATGCCGGCCTTTGAATGGGTTCATGTGCAGCTCCATCAGCAAAAGGGGATGATAAGTTTATCACCACCGACTATTTGCAACAGTGCCCATCTCCGGGTTTATTATATTCGGGCGCATTTGCGCGCGGCAGCTGCTGACTGTTCAGTCTATGTACGCGGAGCCGTTCATGGAAATATTCGCGCAGGTGTTCAGGCTGTTCCCGTTCAACAAGTTCCGGCACGACGGGCTTGTTC
+SRR33475255.3 VH01637:40:AAGVVC2M5:1:1101:32244:1000 length=295
*CCC5CCCCCCCCCCCCCCCCCCCCCCCCCCC5CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC5CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC5CCCCCCCCCCCCCCCCCCCCCCC5CCCCCCC5CCCCCCCCCCCCCC5CCCC*CCCC*CCCCC5CCC*CCCCC5CCCCCCCCCCCCCCCCCCCCCCCCC5CCCCCCCCCCCCCCC*CCCCCCC5CCCCCCCCCCCCCCCCCCCCCCCCCCCC5CCCCCCCCCC5C5C5CCCCCCCCCCCCCC
```

Can you tell how many reads are there in this example output? And what are their IDs, base sequences, and lengths?

::: {.callout-note collapse="false"}
## Challenge

Count the number of forward and reverse reads of sample `AMB201Kp` in a **single command-line**.

*Hint: Use `zgrep` (`grep` for gzipped files) to catch only the sequence ID lines (starting with `@`)*

Correct output: forward = reverse = 617,535 reads
:::

# Reads Quality Control (QC)

We shouldn't trust our data blindly. We will use **FastQC** to generate a report on things like base quality and adapter contamination. 

Since we have many samples, we will then use **MultiQC** to summarize all outputs from **FastQC** into a single, interactive HTML report for all samples.

The following command-lines call the two programs on our short-read data:

``` bash
in_dir="raw_shortread/" # directory for input FASTQ files

fastqc_outdir="fastqc_shortread/" # directory for FastQC outputs
mkdir -p $fastqc_outdir

multiqc_outdir="multiqc_shortread/" # directory for MultiQC output
mkdir -p $multiqc_outdir

# activate the environment with fastqc & multiqc installed
conda activate microgen2026 

nthreads=5 # allows analysing 5 samples in parallel

# run fastqc on all fastq files
fastqc -o $fastqc_outdir -t $nthreads $in_dir/*.fastq.gz 

# run multiqc on all fastqc outputs
multiqc --interactive --force -o $multiqc_outdir $fastqc_outdir 
```

## MultiQC report

Now you can open the file `multiqc_shortread/multiqc_report.html` in your browser to view the report. Or in the VSCode, right click on the file and select "Open Preview".

Let's go through the report and answer the following questions:

- What was the coverage?
- What is the overall quality of the raw reads?
- Are there any adapter contamination?
- Are there any issues with the sequencing?

::: {.callout-important collapse="false"}
## Making decision
Based on the MultiQC report, do you want to improve the raw reads quality? 

If yes, what specific modification to the raw reads would you like to perform? If no, then why?
:::

# Assembly

Assembly is the process of building the full genome by finding overlaps between short reads. We will use **Unicycler**, which is highly regarded for bacterial assembly because it acts as an optimizer for the **SPAdes** assembler.

The syntax for a command that run `unicycler` on a single sample with paired-end reads is as follows:

``` {.bash code-line-numbers="false"}
unicycler -1 $forward -2 $reverse -o $outdir --threads 4
```

where

- `-1` is the forward read file
- `-2` is the reverse read file
- `-o` is the output directory
- `--threads` is the number of threads to use, higher number of threads will speed up the assembly process but will also consume more computing resources.

To do the assembly for our batch of 12 samples in a time-efficient manner, we will automate this using `GNU Parallel`.

``` bash
# create a directory for assembly output
mkdir -p unicycler_shortread

# create a tsv file with sample names and their corresponding fastq files
while read -r sample; do
    echo -e ${sample}"\t"raw_shortread/${sample}_1.fastq.gz"\t"raw_shortread/${sample}_2.fastq.gz >> samples_shortread.tsv;
done < <(grep "Illumina MiSeq" PRJNA1260529.metadata.tsv | cut -f28)

# run unicycler on 3 samples at a time
conda activate microgen2026
parallel -j 3 --colsep "\t" unicycler -1 {2} -2 {3} -o unicycler_shortread/{1} --threads 2 :::: samples_shortread.tsv
```

# Self-Exploration

## Improve reads quality for assembly

In our practice dataset, the quality of the raw sequences were very good. However, in real-life scenarios, this is not always the case.

For example, the raw reads may contain adapter sequences, which are short DNA sequences that are added to the ends of the DNA fragments during the sequencing process. 

OR, we may also often find many low-quality bases at the 3' ends of the reads. These low-quality bases can also interfere with the assembly process, so it is important to remove them before assembly.

All these issues can interfere with the assembly process, and lead to a lower quality assembly. 

Improving reads quality, therefore, is a crucial step before assembly.

To do that, [FASTP](https://github.com/OpenGene/fastp) is a good choice of tool for us.

You are encouraged to read the [FASTP manual](https://github.com/OpenGene/fastp/blob/master/README.md) to understand how it works and how to use it for different modifications on the raw reads.

But to get you started, here is an example command-line:

```bash
fastp --in1 ugly_sample/ERR4244683_1.fastq.gz --in2 ugly_sample/ERR4244683_2.fastq.gz \
    --out1 trimming_output/ERR4244683_1.trimmed.fastq.gz --out2 trimming_output/ERR4244683_2.trimmed.fastq.gz \
    --trim_front1 15 --trim_front2 15 \
    --trim_poly_x \
    --cut_tail --cut_tail_window_size 4 --cut_tail_mean_quality 25 \
    --length_required 50 > trimming_output/fastp_run.log 2>&1
```

The command above does the following things:

- `--in1` and `--in2`: Modifies both the reverse & forward reads of the sample `ERR4244683` in the directory `ugly_sample/`. 
- `--trim_front1` and `--trim_front2`: Trims the first 15 bp from front (5') end
- `--cut_tail`: Moves a sliding window from tail (3') to front
- `--cut_tail_window_size 4`: Sets the sliding window length = 4bp
- `--cut_tail_mean_quality 25`: Drops the bases in the window if its mean quality is below 25. Otherwise, stop the sliding.
- `--trim_poly_x`: Trims the polyX tail
- `--length_required`: Discards all trimmed reads shorter than 50 bp
- Adapter trimming was enabled by default
- `> trimming_output/fastp_run.log 2>&1`: Redirects all messages from the run program to the file `trimming_output/fastp_run.log`

Now,

:::{style="font-size: 1.3em; color: #474747ff; margin-top: 1em; margin-left: 1.7em; margin-bottom: 1em;"} 
How can we know if the trimming was successful, and that the reads quality was improved, but not worsened?
:::

There are 2 main ways to check that:

1. Check the log file `trimming_output/fastp_run.log`, and find:
   - The amount of reads that still remains after trimming and filtering
   - The Q30 percentage of the trimmed reads
2. Compare the MultiQC report of the raw reads and the trimmed reads - Is there any improvement?

To give you a better sense of these, we have an example of a bad quality raw reads in the directory `day-1/ugly_sample/` and the corresponding trimming output in `day-1/trimming_output/`, with the same trimming parameters as above. 

Your tasks will be to explore the files in those directories and answer the questions below:

1. What is bad about the raw reads quality of sample `ERR4244683`?
2. How many reads were removed during the trimming process?
3. Are many reads still remaining after trimming and filtering?
4. What is the Q30 percentage of the trimmed reads?
5. What are the differences in the quality of the trimmed reads compared to the raw reads?
6. Would you use the trimmed reads or the raw reads for assembly? Why?
7. Does it make sense to perform the trimming as in the code above?
8. If you were to change the trimming parameters, what would you change and why?

:::{.callout-tip collapse="true"}
## Run by yourself 🏃🏻‍♀️
We did not ask you to perform this quality improvement step by yourself. <br>
But if you want to, please go ahead and do it! <br>
If you get stucked, you can always refer to the solution in the script: `day-1/script.1.3.sh` <br>
Good luck! 🍀
:::

## Is my isolate really a *K. pneumoniae*?

Species check can be done directly on the raw short-reads sequencing data, thanks to techniques from metagenomics.

Here we introduce the tool named `sylph` that will returns the 'relative abundance' of reads that belonging to different species.

In our case, we would expect to see a near-100% abundance of *Klebsiella pneumoniae* reads.

But let's run the tool on the raw reads first.

``` bash
# path to the database of representative genomes of all microbial species
SYLPH_DB="/databases/sylph/gtdb-r226-c200-dbv1.syldb"

# activate the environment with sylph
conda activate microgen2026

# run sylph on all fastq files
sylph profile $SYLPH_DB -1 raw_shortread/*_1.fastq.gz -2 raw_shortread/*_2.fastq.gz -o sylph_shortread.tsv
```

The program should run very fast.

After getting the output file `sylph_shortread.tsv`, check the relative abundance of *Klebsiella pneumoniae*. Do you see any contamination or mis-identification?

- How the result would look like if there is a co-infection of *Klebsiella pneumoniae* and *Acinetobacter baumannii*?
- How it would be if the isolate was mis-identified as *Klebsiella quasipneumoniae*?
